#!/bin/bash
# NOTE We use Feature Tool ( https://bitbucket.org/ogstudio/feature-tool )
# NOTE to generate different versions from the same source code

dir=`dirname $0`

max_version_id=1

platforms="
desktop
web
"


for id in $(seq 1 $max_version_id); do
    example=$(printf '%02d' "$id")
    echo "Generating example '$example'"
    for platform in $platforms; do
        featuresSpec=$dir/$example/$platform/src/Features.txt
        echo "feature-tool $featuresSpec $dir/features"
        feature-tool $featuresSpec $dir/features
    done
done

