#!/bin/bash
# NOTE We use Feature Tool ( https://bitbucket.org/ogstudio/feature-tool )
# NOTE to generate different versions from the same source code

dir=`dirname $0`

# List of examples.
examples="
01.EmbedResource
02.TextureImage
04.RemoteDebugging
"

# Android platform is processed separately.
platforms="
desktop
web
ios
"

processPlatformFeatures()
{
    PATH_TO_FEATURES_TXT=$1
    PATH_TO_FEATURES=$2
    echo "feature-tool $PATH_TO_FEATURES_TXT $PATH_TO_FEATURES"
    feature-tool $PATH_TO_FEATURES_TXT $PATH_TO_FEATURES
}

main()
{
    for example in $examples; do
        echo "Generating example '$example'"
        for platform in $platforms; do
            processPlatformFeatures $dir/$example/$platform/src/Features.txt $dir/features
        done
        processPlatformFeatures $dir/$example/android/app/src/main/cpp/Features.txt $dir/features
    done
}

main

