#!/bin/bash
# This script generats complete source code for each example
# by using the same source base with the help of
# Feature Tool ( https://bitbucket.org/ogstudio/feature-tool )

# Make sure we have at least Bash 3.
# NOTE Why not Bash 4? Because Apple sucks: https://apple.stackexchange.com/a/197172
if ((BASH_VERSINFO[0] < 3)); then
    echo "ERROR You need to have Bash 3+"
    exit 1
fi

DIR=`dirname $0`
FEATURES_FILENAME=Features.txt

# List of examples.
EXAMPLES="
01.EmbedResource
02.TextureImage
03.HTTPClient
04.RemoteDebugging
05.NodeSelection
"

# Platform -> Path to Features.txt
PLATFORMS=(
    "android"
    "desktop"
    "ios"
    "web"
)
FEATURES=(
    "app/src/main/cpp"
    "src" 
    "src"
    "src"
)

process()
{
    PATH_TO_FEATURES_FILENAME=$1
    FEATURES_FILENAME=$2
    PATH_TO_FEATURES=$3

    PATH_TO_FEATURES_TXT=$PATH_TO_FEATURES_FILENAME/$FEATURES_FILENAME

    echo "feature-tool $PATH_TO_FEATURES_TXT $PATH_TO_FEATURES"
    feature-tool $PATH_TO_FEATURES_TXT $PATH_TO_FEATURES
}

main()
{
    for example in $EXAMPLES; do
        echo "Generating example '$example'"
        for ((i=0; i < ${#PLATFORMS[@]}; i++)); do
            platform=${PLATFORMS[$i]}
            dirFeatures=${FEATURES[$i]}
            # Default features.
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features
            # log
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features/log
            # format
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features/format
            # resource
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features/resource
            # render
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features/render
            # scene
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features/scene
            # network
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features/network
            # debug
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features/debug
            # input
            process $DIR/$example/$platform/$dirFeatures Features.txt $DIR/features/input
        done
    done
}

main

