#!/bin/bash
# This script generats complete source code for each example
# by using the same source base with the help of
# Feature Tool ( https://bitbucket.org/ogstudio/feature-tool )

# Make sure we have at least Bash 3.
# NOTE Why not Bash 4? Because Apple sucks: https://apple.stackexchange.com/a/197172
if ((BASH_VERSINFO[0] < 3)); then
    echo "ERROR You need to have Bash 3+"
    exit 1
fi

DIR=`dirname $0`
FEATURES_FILENAME=Features.txt

# List of examples.
#01.EmbedResource
#02.TextureImage
EXAMPLES="
03.HTTPClient
"

#04.RemoteDebugging
#05.NodeSelection

# Platform -> Path to Features.txt
PLATFORMS=(
    "android"
    "desktop"
    "ios"
    "web"
)

FEATURES_TXT_DIR="src" 
IOS_FEATURES_TXT_DIR="xcodeproject/App"
ANDROID_FEATURES_TXT_DIRS=(
    "app/src/main/cpp"
    "app/src/main/java"
)

FEATURE_DIRS=(
    ""
    "/log"
    "/format"
    "/resource"
    "/render"
    "/scene"
    "/network"
    "/debug"
    "/input"
    "/android"
    "/ios"
)

processFeatureDir()
{
    PATH_TO_FEATURES_FILENAME=$1
    FEATURES_FILENAME=$2
    PATH_TO_FEATURES=$3

    PATH_TO_FEATURES_TXT=$PATH_TO_FEATURES_FILENAME/$FEATURES_FILENAME

    echo "feature-tool $PATH_TO_FEATURES_TXT $PATH_TO_FEATURES"
    feature-tool $PATH_TO_FEATURES_TXT $PATH_TO_FEATURES
}

processFeatureDirs()
{
    dirFeaturesAbs=$1

    for ((id=0; id < ${#FEATURE_DIRS[@]}; id++)); do
        dir=$DIR/features${FEATURE_DIRS[$id]}
        processFeatureDir $dirFeaturesAbs Features.txt $dir
    done
}

main()
{
    for example in $EXAMPLES; do
        echo "Generating example '$example'"

        # For each platform.
        for ((platformId=0; platformId < ${#PLATFORMS[@]}; platformId++)); do
            platform=${PLATFORMS[$platformId]}

            # Desktop. Web. iOS.
            if [ $platform == "desktop" ] || [ $platform == "web" ] || [ $platform == "ios" ]; then
                echo "01. process features for platform '$platform'"
                dirFeaturesAbs=$DIR/$example/$platform/$FEATURES_TXT_DIR
                processFeatureDirs $dirFeaturesAbs
            fi

            # iOS.
            if [ $platform == "ios" ]; then
                echo "02. process features for platform '$platform'"
                dirFeaturesAbs=$DIR/$example/$platform/$IOS_FEATURES_TXT_DIR
                processFeatureDirs $dirFeaturesAbs
            fi

            # Android.
            if [ $platform == "android" ]; then
                echo "03. process features for platform '$platform'"
                for ((dirId=0; dirId < ${#ANDROID_FEATURES_TXT_DIRS[@]}; dirId++)); do
                    dirFeatures=${ANDROID_FEATURES_TXT_DIRS[$dirId]}
                    dirFeaturesAbs=$DIR/$example/$platform/$dirFeatures
                    processFeatureDirs $dirFeaturesAbs
                done
            fi
        done
    done
}

main

