#!/bin/bash

# 3. Replace Billboard's square macro.
fileName="src/osg/Billboard.cpp"
echo "Patching '$fileName'"
sed -i.bak 's|#define square.*||' $fileName

## 1. Replace references to 'osg/GL' header.
#osgGLHeaders="
#include/osg/Array
#include/osg/BufferObject
#include/osg/FrameBufferObject
#include/osg/GLDefines
#include/osg/GLObjects
#include/osg/GLU
#include/osg/PolygonMode
#include/osg/PrimitiveSet
#include/osg/StateAttribute
#include/osg/Texture
#include/osgDB/DataTypes
#"
#
#for file in $osgGLHeaders; do
#    echo "Patching osg/GL referencing header '$file'"
#    sed -i.bak 's|#include <osg/GL>|#include "openscenegraphDefines.h"|' $file
#done
#
## 2. Replace references to 'osg/Config' header.
#osgConfigHeaders="
#include/osg/BoundingBox
#include/osg/BoundingSphere
#include/osg/Export
#include/osg/Matrix
#include/osg/Plane
#include/osg/ref_ptr
#include/osgDB/Export
#include/osgGA/Export
#include/osgUtil/Export
#include/osgViewer/Export
#"
#
#for file in $osgConfigHeaders; do
#    echo "Patching osg/Config referencing header '$file'"
#    sed -i.bak 's|#include<osg/Config>|#include "openscenegraphDefines.h"|' $file
#    sed -i.bak 's|#include <osg/Config>|#include "openscenegraphDefines.h"|' $file
#done

#
## 4. Replace references to 'OpenThreads/Config' header.
#otConfigHeaders="
#include/OpenThreads/Atomic
#include/OpenThreads/Exports
#"
#
#for file in $otConfigHeaders; do
#    echo "Patching OpenThreads/Config referencing header '$file'"
#    sed -i.bak 's|#include <OpenThreads/Config>|#include "openthreadsDefines.h"|' $file
#done
#
## 5. Replace references to 'osg/Version' header.
#osgVersionHeaders="
#include/osgDB/OutputStream
#"
#
#for file in $osgVersionHeaders; do
#    echo "Patching osg/Version referencing header '$file'"
#    sed -i.bak 's|#include <osg/Version>|#include "openscenegraphDefines.h"|' $file
#done
#
